export const PROMOS_LOADING = 'PROMOS_LOADING';
export const PROMOS_FAILED = 'PROMOS_FAILED ';
export const ADD_PROMOS = 'ADD_PROMOS ';
export const RECIPE_LOADING = 'RECIPE_LOADING';
export const ADD_RECIPE = 'ADD_RECIPE';
export const RECIPE_FAILED = 'RECIPE_FAILED';
export const ADD_SINGLERECIPE = 'ADD_SINGLERECIPE';
export const ADD_FEEDBACKS = 'ADD_FEEDBACKS';
export const FEEDBACKS_FAILED = 'FEEDBACKS_FAILED';
export const FEEDBACKS_LOADING = 'FEEDBACKS_LOADING';
export const ADD_FEEDBACK = 'ADD_FEEDBACK';
export const POST_FAVORITE = 'POST_FAVORITE';
export const ADD_FAVORITE = 'ADD_FAVORITE';
export const DELETE_FAVORITE = 'DELETE_FAVORITE';
export const FOUNDERS_LOADING = 'FOUNDERS_LOADING';
export const ADD_FOUNDERS = 'ADD_FOUNDERS';
export const FOUNDERS_FAILED = 'FOUNDERS_FAILED';


